class ActionKind(Enum):
    Walking = 0
    Idle = 1
    Jumping = 2
@namespace
class SpriteKind:
    Gap = SpriteKind.create()

def on_on_overlap(sprite, otherSprite):
    game.over(False, color.rotate_palette)
sprites.on_overlap(SpriteKind.player, SpriteKind.projectile, on_on_overlap)

def createMenu():
    global blueRect, showBlue, yellowRect, showYellow, redRect, showRed
    blueRect = image.create(scene.screen_width(), scene.screen_height() / 3)
    blueRect.fill(7)
    blueRect.draw_rect(0, 0, scene.screen_width(), scene.screen_height() / 3, 7)
    showBlue = sprites.create(blueRect, 0)
    showBlue.set_position(scene.screen_width() / 2, 20)
    yellowRect = image.create(scene.screen_width(), scene.screen_height() / 3)
    yellowRect.fill(1)
    yellowRect.draw_rect(0, 0, scene.screen_width(), scene.screen_height() / 3, 1)
    showYellow = sprites.create(yellowRect, 0)
    showYellow.set_position(scene.screen_width() / 2, 60)
    redRect = image.create(scene.screen_width(), scene.screen_height() / 3)
    redRect.fill(15)
    redRect.draw_rect(0, 0, scene.screen_width(), scene.screen_height() / 3, 15)
    showRed = sprites.create(redRect, 0)
    showRed.set_position(scene.screen_width() / 2, 100)

def on_button_pressed():
    music.knock.play()
    sprite.vy = -100
    animation.set_action(sprite, ActionKind.Jumping)
    sprite.start_effect(effects.blizzard, 500)
controller.any_button.on_event(ControllerButtonEvent.PRESSED, on_button_pressed)

projectile: Sprite = None
bottomImage: Image = None
topImage: Image = None
gap = 0
showRed: Sprite = None
redRect: Image = None
showYellow: Sprite = None
yellowRect: Image = None
showBlue: Sprite = None
blueRect: Image = None
sprite: Sprite = None
scene.set_background_color(9)
info.set_score(-1)
effects.star_field.start_screen_effect()
sprite = sprites.create(assets.tile("""
    Spielfigur
"""), SpriteKind.player)
sprite.set_position(100, 55)
sprite.ay = 300
anim = animation.create_animation(ActionKind.Jumping, 25)
anim.add_animation_frame(assets.image("""
    Spielfigur2
"""))
anim.add_animation_frame(assets.image("""
    Spielfigur3
"""))
anim.add_animation_frame(assets.image("""
    Spielfigur4
"""))
anim.add_animation_frame(assets.image("""
    Spielfigur5
"""))
anim.add_animation_frame(assets.image("""
    Spielfigur6
"""))
anim.add_animation_frame(assets.image("""
    Spielfigur7
"""))
animation.attach_animation(sprite, anim)

def on_on_update():
    if sprite.vy > 0:
        animation.set_action(sprite, ActionKind.Idle)
    if sprite.bottom > 120 or sprite.top < 0:
        game.over(False, color.rotate_palette)
game.on_update(on_on_update)

def on_update_interval():
    global gap, topImage, bottomImage, projectile
    info.change_score_by(1)
    if info.score() != 0:
        music.ba_ding.play()
    gap = randint(0, 3)
    if gap == 0:
        topImage = img("""
            .....6eeeeeeeeeece6.....
                        ....6776eeeeeeeee676....
                        ...6776666eeee6766776...
                        ..6776ee77777777667776..
                        ...668ce7768867788666...
                        ......ce77eeee67ee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......beeeeeeeeeeb......
                        .......beeeeeeeeb.......
                        ........beeeeeeb........
        """)
        bottomImage = img("""
            ........................
                        ........................
                        ..........bbbb..........
                        ........bbddddbb........
                        .......bddbbbbddb.......
                        ......bdbbddddbbdb......
                        .....bdbbdbbbbdbbdb.....
                        .....bdbdbddddbdbdb.....
                        .....cdbbdbbbbdbbdc.....
                        .....cbdbbddddbbdbc.....
                        .....efbddbbbbddbce.....
                        .....eeffbddddbccee.....
                        .....eeeeffcccceee......
                        .....ceeeeeeeeeeee......
                        .....ceeeeeeeeeeee......
                        .....feeeeeeeeeeee......
                        .....cceeeeeeeeeee......
                        ......feeeeeeeeeee......
                        .....6fceeeeeeeeee6.....
                        ....6776eeeeeeeee676....
                        ...6777666eeee6666776...
                        ..67768e67766777667776..
                        ...668ee7768867788666...
                        ......ee77eeee77ecee....
                        ......ee6eeeeee6eef.....
                        ......eeeeeeeeeeeef.....
                        ......eeeeeeeeeeeef.....
                        ......eeeeeeeeeeecf.....
                        ......ceeeeeeeeeecf.....
                        ......ceeeeeeeeeeff.....
                        ......feeeeeeeeeefe.....
                        .....6feeeeeeeeeef6.....
                        ....6776eeeeeeeee676....
                        ...6777666eeee6667776...
                        ..6776ee67777777667776..
                        ...668ee7768867788666...
                        ......ee77eeee67ee......
                        ......ee6eeeeee6ce......
                        ......eefeeeeeeece......
                        ......eeceeeeeeece......
                        ......eeceeeeeeefe......
                        ......eeceeeeeeefe......
                        ......eeeeeeeeeefe......
                        ......eeeeeeeeeece......
                        .....6eeeeeeeeeece6.....
                        ....6776eeeeeeeee676....
                        ...6776666eeee6766776...
                        ..6776ee77777777667776..
                        ...668ce7768867788666...
                        ......ce77eeee67ee......
                        ......ce6eeeeee6ee......
                        ......ceeeeeeeeeee......
                        ......fcceeeeeecee......
                        ......fccceeececce......
                        ......fcceeecceccc......
                        ......fccceecceccc......
                        ......fccccceceecc......
                        .....6fccccccccccf6.....
                        ....6776ccccccccc676....
                        ...6776676cccc6766776...
                        ..6776cc77777777667776..
                        ...668cc7768867788666...
                        ......cc77cccc67cf......
                        ......cc6cccccc6cf......
        """)
    elif gap == 1:
        topImage = img("""
            .....6feeeeeeeeeef6.....
                        ....6776eeeeeeeee676....
                        ...6777666eeee6667776...
                        ..6776ee67777777667776..
                        ...668ee7768867788666...
                        ......ee77eeee67ee......
                        ......ee6eeeeee6ce......
                        ......eefeeeeeeece......
                        ......eeceeeeeeece......
                        ......eeceeeeeeefe......
                        ......eeceeeeeeefe......
                        ......eeeeeeeeeefe......
                        ......eeeeeeeeeece......
                        .....6eeeeeeeeeece6.....
                        ....6776eeeeeeeee676....
                        ...6776666eeee6766776...
                        ..6776ee77777777667776..
                        ...668ce7768867788666...
                        ......ce77eeee67ee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......beeeeeeeeeeb......
                        .......beeeeeeeeb.......
                        ........beeeeeeb........
                        ........................
                        ........................
                        ........................
        """)
        bottomImage = img("""
            ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ..........bbbb..........
                        ........bbddddbb........
                        .......bddbbbbddb.......
                        ......bdbbddddbbdb......
                        .....bdbbdbbbbdbbdb.....
                        .....bdbdbddddbdbdb.....
                        .....cdbbdbbbbdbbdc.....
                        .....cbdbbddddbbdbc.....
                        .....efbddbbbbddbce.....
                        .....eeffbddddbccee.....
                        .....eeeeffcccceee......
                        .....ceeeeeeeeeeee......
                        .....ceeeeeeeeeeee......
                        .....feeeeeeeeeeee......
                        .....cceeeeeeeeeee......
                        ......feeeeeeeeeee......
                        .....6fceeeeeeeeee6.....
                        ....6776eeeeeeeee676....
                        ...6777666eeee6666776...
                        ..67768e67766777667776..
                        ...668ee7768867788666...
                        ......ee77eeee77ecee....
                        ......ee6eeeeee6eef.....
                        ......eeeeeeeeeeeef.....
                        ......eeeeeeeeeeeef.....
                        ......eeeeeeeeeeecf.....
                        ......ceeeeeeeeeecf.....
                        ......ceeeeeeeeeeff.....
                        ......feeeeeeeeeefe.....
                        .....6feeeeeeeeeef6.....
                        ....6776eeeeeeeee676....
                        ...6777666eeee6667776...
                        ..6776ee67777777667776..
                        ...668ee7768867788666...
                        ......ee77eeee67ee......
                        ......ee6eeeeee6ce......
                        ......eefeeeeeeece......
                        ......eeceeeeeeece......
                        ......eeceeeeeeefe......
                        ......eeceeeeeeefe......
                        ......eeeeeeeeeefe......
                        ......eeeeeeeeeece......
                        .....6eeeeeeeeeece6.....
                        ....6776eeeeeeeee676....
                        ...6776666eeee6766776...
                        ..6776ee77777777667776..
                        ...668ce7768867788666...
                        ......ce77eeee67ee......
                        ......ce6eeeeee6ee......
        """)
    elif gap == 2:
        topImage = img("""
            .....6feeeeeeeeeef6.....
                        ....6776eeeeeeeee676....
                        ...6777666eeee6667776...
                        ..6776ee67777777667776..
                        ...668ee7768867788666...
                        ......ee77eeee67eeee....
                        ......ee6eeeeee6cef.....
                        ......eeeeeeeeeeeef.....
                        ......eeeeeeeeeeeef.....
                        ......eeeeeeeeeeecf.....
                        ......eeeeeeeeeeecf.....
                        ......eeeeeeeeeeeff.....
                        ......feeeeeeeeeefe.....
                        .....6feeeeeeeeeef6.....
                        ....6776eeeeeeeee676....
                        ...6777666eeee6667776...
                        ..6776ee67777777667776..
                        ...668ee7768867788666...
                        ......ee77eeee67ee......
                        ......ee6eeeeee6ce......
                        ......eefeeeeeeece......
                        ......eeceeeeeeece......
                        ......eeceeeeeeefe......
                        ......eeceeeeeeefe......
                        ......eeeeeeeeeefe......
                        ......eeeeeeeeeece......
                        .....6eeeeeeeeeece6.....
                        ....6776eeeeeeeee676....
                        ...6776666eeee6766776...
                        ..6776ee77777777667776..
                        ...668ce7768867788666...
                        ......ce77eeee67ee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......beeeeeeeeeeb......
                        .......beeeeeeeeb.......
                        ........beeeeeeb........
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
        """)
        bottomImage = img("""
            ........................
                        ........................
                        ........................
                        ........................
                        ..........bbbb..........
                        ........bbddddbb........
                        .......bddbbbbddb.......
                        ......bdbbddddbbdb......
                        .....bdbbdbbbbdbbdb.....
                        .....bdbdbddddbdbdb.....
                        .....cdbbdbbbbdbbdc.....
                        .....cbdbbddddbbdbc.....
                        .....efbddbbbbddbce.....
                        .....eeffbddddbccee.....
                        .....eeeeffcccceee......
                        .....ceeeeeeeeeeee......
                        .....ceeeeeeeeeeee......
                        .....feeeeeeeeeeee......
                        .....cceeeeeeeeeee......
                        ......feeeeeeeeeee......
                        .....6fceeeeeeeeee6.....
                        ....6776eeeeeeeee676....
                        ...6777666eeee6666776...
                        ..67768e67766777667776..
                        ...668ee7768867788666...
                        ......ee77eeee77ecee....
                        ......ee6eeeeee6eef.....
                        ......eeeeeeeeeeeef.....
                        ......eeeeeeeeeeeef.....
                        ......eeeeeeeeeeecf.....
                        ......ceeeeeeeeeecf.....
                        ......ceeeeeeeeeeff.....
                        ......feeeeeeeeeefe.....
                        .....6feeeeeeeeeef6.....
                        ....6776eeeeeeeee676....
                        ...6777666eeee6667776...
                        ..6776ee67777777667776..
                        ...668ee7768867788666...
                        ......ee77eeee67ee......
                        ......ee6eeeeee6ce......
        """)
    else:
        topImage = img("""
            .....6fceeeeeeeeee6.....
                        ....6776eeeeeeeee676....
                        ...6777666eeee6666776...
                        ..67768e67766777667776..
                        ...668ee7768867788666...
                        ......ee77eeee77ecee....
                        ......ee6eeeeee6eef.....
                        ......eeeeeeeeeeeef.....
                        ......eeeeeeeeeeeef.....
                        ......eeeeeeeeeeecf.....
                        ......ceeeeeeeeeecf.....
                        ......ceeeeeeeeeeff.....
                        ......feeeeeeeeeefe.....
                        .....6feeeeeeeeeef6.....
                        ....6776eeeeeeeee676....
                        ...6777666eeee6667776...
                        ..6776ee67777777667776..
                        ...668ee7768867788666...
                        ......ee77eeee67eeee....
                        ......ee6eeeeee6cef.....
                        ......eeeeeeeeeeeef.....
                        ......eeeeeeeeeeeef.....
                        ......eeeeeeeeeeecf.....
                        ......eeeeeeeeeeecf.....
                        ......eeeeeeeeeeeff.....
                        ......feeeeeeeeeefe.....
                        .....6feeeeeeeeeef6.....
                        ....6776eeeeeeeee676....
                        ...6777666eeee6667776...
                        ..6776ee67777777667776..
                        ...668ee7768867788666...
                        ......ee77eeee67ee......
                        ......ee6eeeeee6ce......
                        ......eefeeeeeeece......
                        ......eeceeeeeeece......
                        ......eeceeeeeeefe......
                        ......eeceeeeeeefe......
                        ......eeeeeeeeeefe......
                        ......eeeeeeeeeece......
                        .....6eeeeeeeeeece6.....
                        ....6776eeeeeeeee676....
                        ...6776666eeee6766776...
                        ..6776ee77777777667776..
                        ...668ce7768867788666...
                        ......ce77eeee67ee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......eeeeeeeeeeee......
                        ......beeeeeeeeeeb......
                        .......beeeeeeeeb.......
                        ........beeeeeeb........
                        ........................
        """)
        bottomImage = img("""
            ........................
                        ..........bbbb..........
                        ........bbddddbb........
                        .......bddbbbbddb.......
                        ......bdbbddddbbdb......
                        .....bdbbdbbbbdbbdb.....
                        .....bdbdbddddbdbdb.....
                        .....cdbbdbbbbdbbdc.....
                        .....cbdbbddddbbdbc.....
                        .....efbddbbbbddbce.....
                        .....eeffbddddbccee.....
                        .....eeeeffcccceee......
                        .....ceeeeeeeeeeee......
                        .....ceeeeeeeeeeee......
                        .....feeeeeeeeeeee......
                        .....cceeeeeeeeeee......
                        ......feeeeeeeeeee......
                        .....6fceeeeeeeeee6.....
                        ....6776eeeeeeeee676....
                        ...6777666eeee6666776...
                        ..67768e67766777667776..
                        ...668ee7768867788666...
                        ......ee77eeee77ecee....
                        ......ee6eeeeee6eef.....
        """)
    projectile = sprites.create_projectile_from_side(topImage, -45, 0)
    projectile.top = 0
    projectile = sprites.create_projectile_from_side(bottomImage, -45, 0)
    projectile.bottom = scene.screen_height()
game.on_update_interval(1500, on_update_interval)

def on_forever():
    music.play_melody("C5 - B - G A B G ", 120 + game.runtime() / 500)
    music.play_melody("C5 - B - A B G - ", 120 + game.runtime() / 500)
forever(on_forever)
